---
title: "Team"
author: "Kenneth Mendoza"
date: "October 23, 2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r data}
library(readxl)
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)
offense <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
bio <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
```

```{r cleanup}
defense$Name = as.factor(defense$Name)
bio$Name = as.factor(bio$Name)
offense$Name = as.factor(offense$Name)
defense$Opponent_Opponent = as.factor(defense$Opponent_Opponent)
offense$Opponent_Opponent = as.factor(offense$Opponent_Opponent)
defense$Tackles_Solo = as.numeric(defense$Tackles_Solo)
defense$Tackles_ASST= as.numeric(defense$Tackles_ASST)
defense$Tackles_TFL= as.numeric(defense$Tackles_TFL)
defense$Tackles_Sack= as.numeric(defense$Tackles_Sack)
defense$Turnover_FF= as.numeric(defense$Turnover_FF)
defense$Turnover_FR= as.numeric(defense$Turnover_FR)
defense$Turnover_INT= as.numeric(defense$Turnover_INT)
defense$Pass_PB= as.numeric(defense$Pass_PB)
defense$Pass_QBH= as.numeric(defense$Pass_QBH)

offense = offense %>% separate(`Passing_CMP-ATT`, c('CMP', 'ATT'),sep = "([-])")

offense$Receiving_REC =as.numeric(offense$Receiving_REC)
offense$Receiving_YDS =as.numeric(offense$Receiving_YDS)
offense$Receiving_TD =as.numeric(offense$Receiving_TD)
offense$Rushing_ATT =as.numeric(offense$Rushing_ATT)
offense$Rushing_YDS =as.numeric(offense$Rushing_YDS)
offense$Rushing_TD =as.numeric(offense$Rushing_TD)
offense$CMP =as.numeric(offense$CMP)
offense$ATT =as.numeric(offense$ATT)
offense$Passing_YDS =as.numeric(offense$Passing_YDS)
offense$Passing_TD =as.numeric(offense$Passing_TD)
offense$Passing_INT =as.numeric(offense$Passing_INT)
```

```{r height}
bioClean =bio %>% separate(Height, c('ft', 'in'),sep = "([-])")
bioClean$ft =as.numeric(bioClean$ft)
bioClean$`in` = as.numeric(bioClean$`in`)
bioClean$Height<-NA
bioClean <- mutate(bioClean,Height= ((ft*12)+`in`))
```

```{r clean}
defClean = defense
offClean = offense
```

```{r tidyr}
defClean = defClean %>% gather(Statistic, Number, 3:11)

defClean$Statistic = as.factor(defClean$Statistic)
ggplot(defClean, aes(Number)) + geom_histogram() + facet_wrap( ~ defClean$Statistic)
```
The Facet Wrap shows that the defensive skill Turnovers are rare.

```{r WV}
School = filter(defClean, Opponent_Opponent == "West Virginia" | Opponent_Opponent == "Kansas State")
School = spread(School, Statistic, Number)

ggplot(School, aes(Tackles_Solo, color = Opponent_Opponent)) + geom_bar() + ggtitle("Kansas State vs. West Virginia")
```
The graph shows that ISU had a better defense against Kansas State.
